version: '3.9'

services:
  web:
    build: .
    container_name: mysql_backup_restore
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data: